### PR TITLE
Check for name collisions between files as they're added to the bag

### LINKED ISSUE #27: Check for name collisions on addFile
Branching from #23 - it would be nice to get an early warning that there's a name collision. When two files (data or tag) are added to a bag and their paths match-throw an exception.

### PR DESCRIPTION
**Pull request by ThomasThelen**
Fixes #27 

Nothing too wild here. I condensed one of the `addFile` methods down, added a private method for checking two paths, and added a unit test to make sure we're throwing when this happens

### CODE REVIEW

File: src/main/java/org/dataone/speedbagit/SpeedBagIt.java [hunk 1]
```diff
@@ -138,19 +137,51 @@ public SpeedBagIt(double version,
...
+
+        /**
+         * Checks whether two paths collide, based on their file type (tag vs data file).
+         *
+         * @param path:  Path being checked against the previously added files
+         * @param isTagFile: A flag whether the file is a data file or not (otherwise it will be a tag)
+         */
+        private boolean hasPathCollisions(String path, boolean isTagFile) {
+            if (isTagFile) {
+                for (SpeedFile tagFile : this.tagFiles) {
```
Comment (mbjones) [inline src/main/java/org/dataone/speedbagit/SpeedBagIt.java]: This loop seems unnecessarily slow -- why use an iterator whiuch searches in O(n) time when you could use a HashSet which searches in O(1) time? This seems true for both this `tagFiles` structure and more importantly, the `dataFiles` structure below.

File: src/main/java/org/dataone/speedbagit/SpeedBagIt.java [hunk 2]
```diff
@@ -138,19 +137,51 @@ public SpeedBagIt(double version,
...
+                    if (Objects.equals(tagFile.getPath(), path)) {
+                        return true;
+                    }
+                }
+            } else {
+                for (SpeedFile dataFile : this.dataFiles) {
```
Comment (mbjones) [inline src/main/java/org/dataone/speedbagit/SpeedBagIt.java]: Same issue here, use a HashSet for O(1) lookups without a loop.

**Review by mbjones — COMMENTED** [review]
Thanks, @ThomasThelen, this is a great move forward. I put in a couple comments on performance for large bags with many items -- seems like a HashSet would be better than the current ArrayList approach, especially of order doesn't matter in the list of files.

One question though -- doesn't this just bump responsibility up to the caller to fix the path name? I guess that makes sense if they decide to rename a conflicting file and call `addFile` again. Is that your intended approach?

File: src/main/java/org/dataone/speedbagit/SpeedBagIt.java (hunk 1 above)
Comment (ThomasThelen) [reply src/main/java/org/dataone/speedbagit/SpeedBagIt.java]: I briefly considered it but went with the existing lists since a hashset would be an additional data structure in memory of size (tag files + data files) and we wouldn't be getting any use out of it other than in this one spot. If we don't mind that-I can do a quick refactor to use the HashSet-just give me a thumbs up! Since this _is_ a critical piece where performance matters, I can see the strong argument for it.

Comment (mbjones) [reply src/main/java/org/dataone/speedbagit/SpeedBagIt.java]: I am suggesting we replace `ArrayList dataFiles` with `HashSet dataFiles`, and same with `tagFiles` throughout. So there would still only be one copy of the list, and memory requirements would be similar. The major difference is in how the list is accessed and appended to. One added advantage of HashSet is that, if you hashed using the path as the key, then the HashSet itself would be able to enforce uniqueness of paths, and you wouldn't even need to access the SpeedFile. I haven't looked through the code comprehensively to see what impact this would have, but with a quick perusal it didn't seem like a major issue to refactor.

Your fix takes care of the existing problem, so it would be perfectly reasonable to fix that and then later refactor for performance. It just jumped out to me. And I do think performance is an issue with this list.

Comment (ThomasThelen) [reply src/main/java/org/dataone/speedbagit/SpeedBagIt.java]: 378f591569b5365524bf483488561951e8bda0cd has this implemented as `HashMap<String, SpeedFile>`. The three areas of interest are 
1. [Where we add to it](https://github.com/DataONEorg/speed-bagit/pull/28/commits/378f591569b5365524bf483488561951e8bda0cd#diff-d096abe3162e8756944f3ff751fdec9bd2e56e192fa6d358a52dae4f012f4cfcR144)
2. [Where we use it for path collision lookup](https://github.com/DataONEorg/speed-bagit/pull/28/commits/378f591569b5365524bf483488561951e8bda0cd#diff-d096abe3162e8756944f3ff751fdec9bd2e56e192fa6d358a52dae4f012f4cfcR158)
3. [Where we iterate over it](https://github.com/DataONEorg/speed-bagit/pull/28/commits/378f591569b5365524bf483488561951e8bda0cd#diff-d096abe3162e8756944f3ff751fdec9bd2e56e192fa6d358a52dae4f012f4cfcR301)

Slightly unrelated change: I simplified [this](https://github.com/DataONEorg/speed-bagit/pull/28/commits/378f591569b5365524bf483488561951e8bda0cd#diff-d096abe3162e8756944f3ff751fdec9bd2e56e192fa6d358a52dae4f012f4cfcL121) constructor by making use of the _other_ constructor. 

[70c63af](https://github.com/DataONEorg/speed-bagit/pull/28/commits/70c63af43b3f40f0e62f6d44b01693208bdaad5b) has a version bump so that it'll be ready to be shipped off to maven.

If there's anything else that you see LMK. All in all I think this was a really good change to get in

**Review by mbjones — APPROVED** [review]
Thanks, this looks good and it passes test for me. This leaves responsibility with the client to deal with exceptions from duplicate filenames, which seems like the right choice.
